# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.define :node do |node| 
        node.vm.box = "precise64"
        node.vm.network :private_network, ip: "192.168.33.10"
        node.vm.hostname = "node1.example.com"
        
        node.vm.provider :virtualbox do |vb|
            # Use VBoxManage to customize the VM. For example to change memory:
            vb.customize ["modifyvm", :id, "--memory", "512"]
        end
  
        node.vm.provision :puppet  do |puppet|
            puppet.manifests_path = "manifests"
            puppet.manifest_file  = "site.pp"
            puppet.module_path = "../../modules"
            puppet.options = "--verbose --debug"
            puppet.facter = { 
                'fqdn' => node.vm.hostname,
                :vagrant => true
            }
        end
    end

end
