# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.define :master, primary: true do |master| 
        master.vm.box = "precise64"
        #master.vm.forward_port 8080, 8080
        master.vm.network :private_network, ip: "192.168.33.10"
        master.vm.hostname = "ci-master.example.com"
        
        master.vm.provider :virtualbox do |vb|
            # Use VBoxManage to customize the VM. For example to change memory:
            vb.customize ["modifyvm", :id, "--memory", "512"]
        end
  
        master.vm.provision :puppet  do |puppet|
            puppet.manifests_path = "manifests"
            puppet.manifest_file  = "master-node.pp"
            puppet.module_path = "../../modules"
            puppet.facter = { 'fqdn' => master.vm.hostname }
        end
    end

    config.vm.define :slave1 do |slave| 
        slave.vm.box = "precise64"
  
        slave.vm.network :private_network, ip: "192.168.33.11"
        slave.vm.hostname = "ci-slave-1.example.com"
  
        slave.vm.provider :virtualbox do |vb|  
            # Use VBoxManage to customize the VM. For example to change memory:
            vb.customize ["modifyvm", :id, "--memory", "512"]
        end
  
        slave.vm.provision :puppet  do |puppet|
            puppet.manifests_path = "manifests"
            puppet.manifest_file  = "slave-node.pp"
            puppet.module_path = "../../modules"
            puppet.facter = { 'fqdn' => slave.vm.hostname }
        end
    end

    config.vm.define :slave2 do |slave| 
        slave.vm.box = "precise64"
  
        slave.vm.network :private_network, ip: "192.168.33.12"
        slave.vm.hostname = "ci-slave-2.example.com"
  
        slave.vm.provider :virtualbox do |vb|  
            # Use VBoxManage to customize the VM. For example to change memory:
            vb.customize ["modifyvm", :id, "--memory", "512"]
        end
  
        slave.vm.provision :puppet  do |puppet|
            puppet.manifests_path = "manifests"
            puppet.manifest_file  = "slave-node.pp"
            puppet.module_path = "../../modules"
            puppet.facter = { 'fqdn' => slave.vm.hostname }
        end
    end

end
